services:
  backend:
    build: .
    container_name: nest_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: mi_basedatos
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mi_basedatos
    ports:
      - "5433:5432"  # Puerto externo (host):interno (contenedor)
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data
