services:
  backend:
    build: .
    container_name: nest_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mi_basedatos
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev  # usa start:dev si tienes hot reload configurado

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mi_basedatos
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
